### ISSUE TITLE
Conversion failed when converting value to data type

### ISSUE THREAD

**Issue by Yevrag35** [Ioan-Popovici/SCCM-Zone#11]
Running the report gives me:
![conversionfailed](https://user-images.githubusercontent.com/20248838/53521508-4bab2400-3aa6-11e9-98fd-ff69e80d7f49.png)
How do I begin debugging this?

**Comment by Ioan-Popovici** [comment]
moved to the new repo this will one will be deleted.
Please follow up on the progress there
https://github.com/SCCM-Zone/sccm-zone.github.io/issues/4
